from enum import IntEnum


class AttachPoint(IntEnum):
	none = 0
	head = 2				#skull				head
	nose = 17				#nose				nose
	mouth = 11				#mouth				mouth
	face_tongue = 52		#tongue				tongue
	chin = 12				#chin				chin
	face_jaw = 47			#jaw				jaw
	lear = 13				#left ear			left ear
	rear = 14				#right ear			right ear
	face_lear = 48			#alt left ear		left ear (extended)
	face_rear = 49			#alt right ear		right ear (extended)
	leye = 15				#left eye			left eye
	reye = 16				#right eye			right eye
	face_leye = 50			#alt left eye		left eye (extended)
	face_reye = 51			#alt right eye		right eye (extended)
	neck = 39				#neck				neck
	lshoulder = 3			#left shoulder		left shoulder
	rshoulder = 4			#right shoulder		right shoulder
	luarm = 20				#l upper arm		left upper arm
	ruarm = 18				#r upper arm		right upper arm
	llarm = 21				#l lower arm		left lower arm
	rlarm = 19				#r lower arm		right lower arm
	lhand = 5				#left hand			left hand
	rhand = 6				#right hand			right hand
	lhand_ring1 = 41		#left ring finger	left ring finger
	rhand_ring1 = 42		#right ring finger	right ring finger
	lwing = 45				#left wing			left wing
	rwing = 46				#right wing			right wing
	chest = 1				#chest				chest/sternum
	left_pec = 29			#left pec			left pectoral
	right_pec = 30			#right pec			right pectoral
	belly = 28				#stomach			belly/stomach/tummy
	back = 9				#spine				back
	tail_base = 43			#tail base			tail base
	tail_tip = 44			#tail tip			tail tip
	avatar_center = 40		#avatar center		avatar center/root
	pelvis = 10				#pelvis				pelvis
	groin = 53				#groin				groin
	lhip = 25				#left hip			left hip
	rhip = 22				#right hip			right hip
	luleg = 26				#l upper leg		left upper leg
	ruleg = 23				#r upper leg		right upper leg
	rlleg = 24				#r lower leg		right lower leg
	llleg = 27				#l lower leg		left lower leg
	lfoot = 7				#left foot			left foot
	rfoot = 8				#right foot			right foot
	hind_lfoot = 54			#left hind foot		left hind foot
	hind_rfoot = 55			#right hind foot	right hind foot

	hud_center_2 = 31		#hud center 2
	hud_top_right = 32		#hud top right
	hud_top_center = 33		#hud top
	hud_top_left = 34		#hud top left
	hud_center_1 = 35		#hud center
	hud_bottom_left = 36	#hud bottom left
	hud_bottom = 37			#hud bottom
	hud_bottom_right = 38	#hud bottom right
